import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialSchema1778025257610 implements MigrationInterface {
    name = 'InitialSchema1778025257610'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TYPE "public"."wallets_status_enum" AS ENUM('active', 'frozen', 'closed')`);
        await queryRunner.query(`CREATE TABLE "wallets" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "balance" bigint NOT NULL DEFAULT '0', "currency" character varying(3) NOT NULL DEFAULT 'XOF', "status" "public"."wallets_status_enum" NOT NULL DEFAULT 'active', "daily_withdrawal_limit" bigint NOT NULL DEFAULT '10000000', "version" integer NOT NULL DEFAULT '0', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_92558c08091598f7a4439586cda" UNIQUE ("user_id"), CONSTRAINT "PK_8402e5df5a30a229380e83e4f7e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "idx_wallets_user" ON "wallets" ("user_id") `);
        await queryRunner.query(`CREATE TYPE "public"."wallet_transactions_type_enum" AS ENUM('credit', 'debit')`);
        await queryRunner.query(`CREATE TYPE "public"."wallet_transactions_reason_enum" AS ENUM('ride_payment', 'ride_earning', 'delivery_payment', 'delivery_earning', 'food_payment', 'topup', 'withdrawal', 'referral_bonus', 'promo_credit', 'refund', 'admin_adjustment')`);
        await queryRunner.query(`CREATE TABLE "wallet_transactions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "wallet_id" uuid NOT NULL, "type" "public"."wallet_transactions_type_enum" NOT NULL, "reason" "public"."wallet_transactions_reason_enum" NOT NULL, "amount" bigint NOT NULL, "balance_after" bigint NOT NULL, "currency" character varying(3) NOT NULL DEFAULT 'XOF', "reference_id" uuid, "description" text, "metadata" jsonb, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_5120f131bde2cda940ec1a621db" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_wtx_wallet_type" ON "wallet_transactions" ("wallet_id", "type", "created_at") `);
        await queryRunner.query(`CREATE INDEX "idx_wtx_reference" ON "wallet_transactions" ("reference_id", "reason") `);
        await queryRunner.query(`CREATE INDEX "idx_wtx_wallet" ON "wallet_transactions" ("wallet_id", "created_at") `);
        await queryRunner.query(`CREATE TYPE "public"."users_status_enum" AS ENUM('active', 'inactive', 'suspended', 'pending_kyc')`);
        await queryRunner.query(`CREATE TABLE "users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "firstName" character varying(100) NOT NULL, "lastName" character varying(100) NOT NULL, "phone" character varying(20) NOT NULL, "email" character varying(255), "passwordHash" character varying(255) NOT NULL, "status" "public"."users_status_enum" NOT NULL DEFAULT 'active', "city_id" uuid NOT NULL, "referral_code" character varying(20) NOT NULL, "referred_by_id" uuid, "avatar_url" character varying(255), "fcm_token" character varying(500), "phone_verified" boolean NOT NULL DEFAULT false, "kyc_verified" boolean NOT NULL DEFAULT false, "metadata" jsonb, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, CONSTRAINT "UQ_a000cca60bcf04454e727699490" UNIQUE ("phone"), CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"), CONSTRAINT "UQ_ba10055f9ef9690e77cf6445cba" UNIQUE ("referral_code"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_users_created" ON "users" ("created_at") `);
        await queryRunner.query(`CREATE INDEX "idx_users_city_status" ON "users" ("city_id", "status") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "idx_users_referral" ON "users" ("referral_code") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "idx_users_email" ON "users" ("email") WHERE "email" IS NOT NULL`);
        await queryRunner.query(`CREATE UNIQUE INDEX "idx_users_phone" ON "users" ("phone") `);
        await queryRunner.query(`CREATE TYPE "public"."user_kyc_status_enum" AS ENUM('pending', 'approved', 'rejected')`);
        await queryRunner.query(`CREATE TABLE "user_kyc" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "status" "public"."user_kyc_status_enum" NOT NULL DEFAULT 'pending', "id_card_front_url" character varying(500) NOT NULL, "id_card_back_url" character varying(500), "selfie_url" character varying(500) NOT NULL, "address_proof_url" character varying(500), "rejection_reason" text, "reviewed_by" uuid, "reviewed_at" TIMESTAMP, "submitted_at" TIMESTAMP NOT NULL DEFAULT NOW(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_53ae38d2ed5bc33a3cb7e3fb1e3" UNIQUE ("user_id"), CONSTRAINT "PK_96852e5a0116c49c1507faae57a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_user_kyc_status" ON "user_kyc" ("status") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "idx_user_kyc_user" ON "user_kyc" ("user_id") `);
        await queryRunner.query(`CREATE TYPE "public"."rides_type_enum" AS ENUM('moto', 'car', 'carpool')`);
        await queryRunner.query(`CREATE TYPE "public"."rides_status_enum" AS ENUM('pending', 'searching', 'accepted', 'driver_en_route', 'arrived', 'in_progress', 'completed', 'cancelled', 'scheduled', 'no_driver')`);
        await queryRunner.query(`CREATE TYPE "public"."rides_cancelled_by_enum" AS ENUM('user', 'driver', 'system', 'admin')`);
        await queryRunner.query(`CREATE TABLE "rides" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "driver_id" uuid, "city_id" uuid NOT NULL, "type" "public"."rides_type_enum" NOT NULL, "status" "public"."rides_status_enum" NOT NULL DEFAULT 'pending', "pickup_address" character varying(500) NOT NULL, "pickup_lat" numeric(10,7) NOT NULL, "pickup_lng" numeric(10,7) NOT NULL, "dropoff_address" character varying(500) NOT NULL, "dropoff_lat" numeric(10,7) NOT NULL, "dropoff_lng" numeric(10,7) NOT NULL, "estimated_price" numeric(12,2) NOT NULL, "final_price" numeric(12,2), "currency" character varying(3) NOT NULL DEFAULT 'XOF', "surge_factor" numeric(4,2) NOT NULL DEFAULT '1', "pricing_rule_id" uuid, "distance_km" numeric(8,3), "duration_seconds" integer, "accepted_at" TIMESTAMP, "started_at" TIMESTAMP, "completed_at" TIMESTAMP, "cancelled_at" TIMESTAMP, "scheduled_at" TIMESTAMP, "cancelled_by" "public"."rides_cancelled_by_enum", "cancellation_reason" character varying(500), "payment_id" uuid, "is_paid" boolean NOT NULL DEFAULT false, "user_rating" integer, "driver_rating" integer, "user_comment" text, "metadata" jsonb, "modification_count" integer NOT NULL DEFAULT '0', "modification_fee_total_xof" integer NOT NULL DEFAULT '0', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_ca6f62fc1e999b139c7f28f07fd" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_rides_status" ON "rides" ("status") `);
        await queryRunner.query(`CREATE INDEX "idx_rides_scheduled" ON "rides" ("scheduled_at") WHERE "status" = 'scheduled'`);
        await queryRunner.query(`CREATE INDEX "idx_rides_city" ON "rides" ("city_id", "status", "created_at") `);
        await queryRunner.query(`CREATE INDEX "idx_rides_driver_status" ON "rides" ("driver_id", "status") `);
        await queryRunner.query(`CREATE INDEX "idx_rides_user_status" ON "rides" ("user_id", "status", "created_at") `);
        await queryRunner.query(`CREATE TYPE "public"."ride_modification_logs_field_enum" AS ENUM('dropoff_address', 'dropoff_coords', 'scheduled_at', 'ride_type', 'pickup_address', 'pickup_coords')`);
        await queryRunner.query(`CREATE TYPE "public"."ride_modification_logs_phase_enum" AS ENUM('pre_acceptance', 'pre_departure', 'in_progress')`);
        await queryRunner.query(`CREATE TABLE "ride_modification_logs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "ride_id" uuid NOT NULL, "modified_by_id" uuid NOT NULL, "field" "public"."ride_modification_logs_field_enum" NOT NULL, "phase" "public"."ride_modification_logs_phase_enum" NOT NULL, "old_value" text NOT NULL, "new_value" text NOT NULL, "modification_fee_xof" integer NOT NULL DEFAULT '0', "ride_status_at_modification" character varying(30) NOT NULL, "old_estimated_price" numeric(12,2) NOT NULL, "new_estimated_price" numeric(12,2) NOT NULL, "reason" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_57ebab46a7550f4f2ef0e82dac6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_rml_user" ON "ride_modification_logs" ("modified_by_id") `);
        await queryRunner.query(`CREATE INDEX "idx_rml_ride" ON "ride_modification_logs" ("ride_id", "created_at") `);
        await queryRunner.query(`CREATE TYPE "public"."referral_usages_status_enum" AS ENUM('pending', 'completed', 'rewarded', 'expired', 'aborted')`);
        await queryRunner.query(`CREATE TABLE "referral_usages" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "program_id" uuid NOT NULL, "city_id" uuid NOT NULL, "referrer_id" uuid NOT NULL, "referee_id" uuid NOT NULL, "status" "public"."referral_usages_status_enum" NOT NULL DEFAULT 'pending', "trips_completed" integer NOT NULL DEFAULT '0', "trigger_service_type" character varying(20), "trigger_order_id" uuid, "device_fingerprint" character varying(64), "registration_ip" character varying(45), "phone_prefix" character varying(20), "rewarded_at" TIMESTAMP, "expires_at" TIMESTAMP, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_021598dec0aae784a5835b11714" UNIQUE ("referee_id"), CONSTRAINT "PK_3ad28d39f0937eccddb4795f24d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_ru_city_program" ON "referral_usages" ("city_id", "program_id") `);
        await queryRunner.query(`CREATE INDEX "idx_ru_program" ON "referral_usages" ("program_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "idx_ru_referee" ON "referral_usages" ("referee_id") `);
        await queryRunner.query(`CREATE INDEX "idx_ru_referrer" ON "referral_usages" ("referrer_id", "status") `);
        await queryRunner.query(`CREATE TYPE "public"."referral_reward_logs_recipient_role_enum" AS ENUM('referrer', 'referee')`);
        await queryRunner.query(`CREATE TYPE "public"."referral_reward_logs_status_enum" AS ENUM('pending', 'granted', 'failed', 'reversed')`);
        await queryRunner.query(`CREATE TABLE "referral_reward_logs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "referral_usage_id" uuid NOT NULL, "program_id" uuid NOT NULL, "city_id" uuid NOT NULL, "referrer_id" uuid NOT NULL, "referee_id" uuid NOT NULL, "recipient_id" uuid NOT NULL, "recipient_role" "public"."referral_reward_logs_recipient_role_enum" NOT NULL, "trigger_order_id" uuid NOT NULL, "service_type" character varying(20) NOT NULL, "amount_xof" bigint NOT NULL, "wallet_tx_id" uuid, "status" "public"."referral_reward_logs_status_enum" NOT NULL DEFAULT 'pending', "failure_reason" character varying(255), "idempotency_key" character varying(120) NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_291bef17777e6f309bb8e47f478" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "idx_rrl_idempotency" ON "referral_reward_logs" ("idempotency_key") `);
        await queryRunner.query(`CREATE INDEX "idx_rrl_program" ON "referral_reward_logs" ("program_id", "created_at") `);
        await queryRunner.query(`CREATE INDEX "idx_rrl_city_service" ON "referral_reward_logs" ("city_id", "service_type", "created_at") `);
        await queryRunner.query(`CREATE INDEX "idx_rrl_referee" ON "referral_reward_logs" ("referee_id") `);
        await queryRunner.query(`CREATE INDEX "idx_rrl_referrer" ON "referral_reward_logs" ("referrer_id", "created_at") `);
        await queryRunner.query(`CREATE INDEX "idx_rrl_usage" ON "referral_reward_logs" ("referral_usage_id") `);
        await queryRunner.query(`CREATE TYPE "public"."referral_programs_referrer_reward_type_enum" AS ENUM('wallet_credit', 'discount', 'free_ride')`);
        await queryRunner.query(`CREATE TYPE "public"."referral_programs_referee_reward_type_enum" AS ENUM('wallet_credit', 'discount', 'free_ride')`);
        await queryRunner.query(`CREATE TABLE "referral_programs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(100) NOT NULL, "city_id" uuid, "service_types" jsonb NOT NULL DEFAULT '["ride"]', "referrer_reward_type" "public"."referral_programs_referrer_reward_type_enum" NOT NULL, "referrer_reward_amount" bigint NOT NULL, "max_rewards_per_referrer" integer NOT NULL DEFAULT '0', "referee_reward_type" "public"."referral_programs_referee_reward_type_enum" NOT NULL, "referee_reward_amount" bigint NOT NULL, "trigger_after_trips" integer NOT NULL DEFAULT '1', "min_trigger_amount_xof" bigint NOT NULL DEFAULT '0', "anti_abuse_config" jsonb NOT NULL DEFAULT '{}', "expires_at" TIMESTAMP, "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_5aa525f195d44299e66d8830779" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_rp_global_active" ON "referral_programs" ("is_active") `);
        await queryRunner.query(`CREATE INDEX "idx_rp_city_active" ON "referral_programs" ("city_id", "is_active") `);
        await queryRunner.query(`CREATE TYPE "public"."pricing_rules_service_type_enum" AS ENUM('moto', 'car', 'carpool', 'delivery', 'food')`);
        await queryRunner.query(`CREATE TABLE "pricing_rules" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "city_id" uuid NOT NULL, "service_type" "public"."pricing_rules_service_type_enum" NOT NULL, "name" character varying(100) NOT NULL, "base_fare" numeric(10,2) NOT NULL, "per_km_rate" numeric(8,2) NOT NULL, "per_minute_rate" numeric(8,2) NOT NULL, "minimum_fare" numeric(10,2) NOT NULL, "maximum_fare" numeric(10,2), "surge_multiplier" numeric(4,2) NOT NULL DEFAULT '1', "currency" character varying(3) NOT NULL DEFAULT 'XOF', "time_conditions" jsonb, "day_conditions" jsonb, "priority" integer NOT NULL DEFAULT '0', "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_fda27bb8db4630894decda61ff6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_pricing_priority" ON "pricing_rules" ("city_id", "service_type", "priority") `);
        await queryRunner.query(`CREATE INDEX "idx_pricing_city_service" ON "pricing_rules" ("city_id", "service_type", "is_active") `);
        await queryRunner.query(`CREATE TYPE "public"."city_pricing_configs_service_type_enum" AS ENUM('moto', 'car', 'carpool', 'delivery', 'food')`);
        await queryRunner.query(`CREATE TABLE "city_pricing_configs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "city_id" uuid NOT NULL, "service_type" "public"."city_pricing_configs_service_type_enum" NOT NULL, "rule_key" character varying(60) NOT NULL, "name" character varying(120) NOT NULL, "params" jsonb NOT NULL DEFAULT '{}', "conditions" jsonb, "priority" integer NOT NULL DEFAULT '10', "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_57c0dae879b28cffaa4e9ca97c7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_cpc_city_service_priority" ON "city_pricing_configs" ("city_id", "service_type", "priority") `);
        await queryRunner.query(`CREATE INDEX "idx_cpc_city_service_active" ON "city_pricing_configs" ("city_id", "service_type", "is_active") `);
        await queryRunner.query(`CREATE TYPE "public"."payments_service_type_enum" AS ENUM('ride', 'delivery', 'food', 'wallet_topup', 'withdrawal')`);
        await queryRunner.query(`CREATE TYPE "public"."payments_status_enum" AS ENUM('pending', 'processing', 'success', 'failed', 'refunded', 'cancelled')`);
        await queryRunner.query(`CREATE TYPE "public"."payments_provider_enum" AS ENUM('orange_money', 'moov_money', 'coris_bank', 'wallet', 'cash')`);
        await queryRunner.query(`CREATE TABLE "payments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "service_type" "public"."payments_service_type_enum" NOT NULL, "reference_id" uuid NOT NULL, "amount" numeric(12,2) NOT NULL, "currency" character varying(3) NOT NULL DEFAULT 'XOF', "status" "public"."payments_status_enum" NOT NULL DEFAULT 'pending', "provider" "public"."payments_provider_enum" NOT NULL, "provider_phone" character varying(20), "provider_tx_id" character varying(255), "provider_response" jsonb, "paid_at" TIMESTAMP, "retry_count" integer NOT NULL DEFAULT '0', "failure_reason" text, "metadata" jsonb, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_197ab7af18c93fbb0c9b28b4a59" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_payments_pending" ON "payments" ("status", "created_at") WHERE "status" IN ('pending', 'processing')`);
        await queryRunner.query(`CREATE INDEX "idx_payments_provider_tx" ON "payments" ("provider_tx_id") WHERE "provider_tx_id" IS NOT NULL`);
        await queryRunner.query(`CREATE INDEX "idx_payments_reference" ON "payments" ("reference_id", "service_type") `);
        await queryRunner.query(`CREATE INDEX "idx_payments_user" ON "payments" ("user_id", "status", "created_at") `);
        await queryRunner.query(`CREATE TABLE "city_payment_configs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "city_id" uuid NOT NULL, "provider" character varying(50) NOT NULL, "is_enabled" boolean NOT NULL DEFAULT true, "config" jsonb NOT NULL, "fee_percent" numeric(5,4) NOT NULL DEFAULT '0', "fee_fixed" bigint NOT NULL DEFAULT '0', "priority" integer NOT NULL DEFAULT '0', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_44b91592a07954868540ce05eb8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "idx_cpc_city_provider" ON "city_payment_configs" ("city_id", "provider") `);
        await queryRunner.query(`CREATE TYPE "public"."notifications_channel_enum" AS ENUM('push', 'sms', 'email', 'in_app', 'websocket')`);
        await queryRunner.query(`CREATE TYPE "public"."notifications_category_enum" AS ENUM('ride', 'payment', 'promo', 'system', 'referral', 'delivery', 'food')`);
        await queryRunner.query(`CREATE TYPE "public"."notifications_status_enum" AS ENUM('pending', 'queued', 'sent', 'delivered', 'failed', 'read', 'scheduled', 'cancelled')`);
        await queryRunner.query(`CREATE TYPE "public"."notifications_priority_enum" AS ENUM('low', 'normal', 'high', 'critical')`);
        await queryRunner.query(`CREATE TABLE "notifications" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "channel" "public"."notifications_channel_enum" NOT NULL, "category" "public"."notifications_category_enum" NOT NULL, "status" "public"."notifications_status_enum" NOT NULL DEFAULT 'pending', "priority" "public"."notifications_priority_enum" NOT NULL DEFAULT 'normal', "title" character varying(250) NOT NULL, "body" text NOT NULL, "data" jsonb, "city_id" uuid, "target_role" character varying(50), "device_token" text, "recipient_email" character varying(255), "recipient_phone" character varying(25), "provider_message_id" character varying(255), "retry_count" integer NOT NULL DEFAULT '0', "max_retries" integer NOT NULL DEFAULT '3', "next_retry_at" TIMESTAMP, "scheduled_at" TIMESTAMP, "sent_at" TIMESTAMP, "delivered_at" TIMESTAMP, "read_at" TIMESTAMP, "failure_reason" text, "queue_job_id" character varying(255), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_6a72c3c0f683f6462415e653c3a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_notif_city" ON "notifications" ("city_id", "created_at") `);
        await queryRunner.query(`CREATE INDEX "idx_notif_scheduled" ON "notifications" ("scheduled_at", "status") WHERE "status" = 'scheduled'`);
        await queryRunner.query(`CREATE INDEX "idx_notif_category" ON "notifications" ("user_id", "category") `);
        await queryRunner.query(`CREATE INDEX "idx_notif_unread" ON "notifications" ("user_id", "status") WHERE "status" IN ('pending','queued','sent','delivered')`);
        await queryRunner.query(`CREATE INDEX "idx_notif_user" ON "notifications" ("user_id", "status", "created_at") `);
        await queryRunner.query(`CREATE TYPE "public"."notification_delivery_logs_channel_enum" AS ENUM('push', 'sms', 'email', 'in_app', 'websocket')`);
        await queryRunner.query(`CREATE TYPE "public"."notification_delivery_logs_status_enum" AS ENUM('success', 'failure')`);
        await queryRunner.query(`CREATE TABLE "notification_delivery_logs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "notification_id" uuid NOT NULL, "attempt" smallint NOT NULL DEFAULT '1', "channel" "public"."notification_delivery_logs_channel_enum" NOT NULL, "provider" character varying(60) NOT NULL, "status" "public"."notification_delivery_logs_status_enum" NOT NULL, "status_code" integer, "provider_message_id" character varying(255), "error_detail" text, "duration_ms" integer, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_7d02cbec99bc30d81d79705caa0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_ndl_status" ON "notification_delivery_logs" ("status", "created_at") `);
        await queryRunner.query(`CREATE INDEX "idx_ndl_notification" ON "notification_delivery_logs" ("notification_id", "attempt") `);
        await queryRunner.query(`CREATE TYPE "public"."broadcast_notifications_status_enum" AS ENUM('pending', 'processing', 'completed', 'failed', 'cancelled')`);
        await queryRunner.query(`CREATE TABLE "broadcast_notifications" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_by" uuid NOT NULL, "target_city_id" uuid, "target_role" character varying(50), "title" character varying(250) NOT NULL, "body" text NOT NULL, "data" jsonb, "channels" jsonb NOT NULL DEFAULT '["push","in_app"]', "filters" jsonb, "status" "public"."broadcast_notifications_status_enum" NOT NULL DEFAULT 'pending', "total_recipients" integer NOT NULL DEFAULT '0', "sent_count" integer NOT NULL DEFAULT '0', "failed_count" integer NOT NULL DEFAULT '0', "scheduled_at" TIMESTAMP, "started_at" TIMESTAMP, "completed_at" TIMESTAMP, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_95e28f6ac16c345d02f9a2d15e0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_broadcast_city_role" ON "broadcast_notifications" ("target_city_id", "target_role") `);
        await queryRunner.query(`CREATE INDEX "idx_broadcast_status" ON "broadcast_notifications" ("status", "scheduled_at") `);
        await queryRunner.query(`CREATE TABLE "restaurants" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "owner_id" uuid NOT NULL, "city_id" uuid NOT NULL, "name" character varying(150) NOT NULL, "slug" character varying(150) NOT NULL, "category" character varying(100), "address" character varying(500) NOT NULL, "lat" numeric(10,7) NOT NULL, "lng" numeric(10,7) NOT NULL, "phone" character varying(20), "rating" numeric(3,2) NOT NULL DEFAULT '5', "is_active" boolean NOT NULL DEFAULT true, "is_open" boolean NOT NULL DEFAULT false, "opening_hours" jsonb, "metadata" jsonb, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_afb6330c019768b4c3f9a65303c" UNIQUE ("slug"), CONSTRAINT "PK_e2133a72eb1cc8f588f7b503e68" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "idx_rest_slug" ON "restaurants" ("slug") `);
        await queryRunner.query(`CREATE INDEX "idx_rest_city" ON "restaurants" ("city_id", "is_active") `);
        await queryRunner.query(`CREATE TYPE "public"."food_orders_status_enum" AS ENUM('pending', 'confirmed', 'preparing', 'ready_for_pickup', 'picked_up', 'delivered', 'cancelled')`);
        await queryRunner.query(`CREATE TABLE "food_orders" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "restaurant_id" uuid NOT NULL, "driver_id" uuid, "status" "public"."food_orders_status_enum" NOT NULL DEFAULT 'pending', "items" jsonb NOT NULL, "subtotal" numeric(12,2) NOT NULL, "delivery_fee" numeric(12,2) NOT NULL, "discount" numeric(12,2) NOT NULL DEFAULT '0', "total" numeric(12,2) NOT NULL, "currency" character varying(3) NOT NULL DEFAULT 'XOF', "delivery_address" character varying(500) NOT NULL, "delivery_lat" numeric(10,7) NOT NULL, "delivery_lng" numeric(10,7) NOT NULL, "special_instructions" text, "payment_id" uuid, "is_paid" boolean NOT NULL DEFAULT false, "estimated_delivery_at" TIMESTAMP, "delivered_at" TIMESTAMP, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_b5765853128905c515770b51a04" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_fo_driver" ON "food_orders" ("driver_id", "status") `);
        await queryRunner.query(`CREATE INDEX "idx_fo_restaurant" ON "food_orders" ("restaurant_id", "status") `);
        await queryRunner.query(`CREATE INDEX "idx_fo_user" ON "food_orders" ("user_id", "status", "created_at") `);
        await queryRunner.query(`CREATE TYPE "public"."drivers_status_enum" AS ENUM('pending_approval', 'active', 'suspended', 'offline', 'online', 'on_trip')`);
        await queryRunner.query(`CREATE TYPE "public"."drivers_vehicletype_enum" AS ENUM('moto', 'car', 'pickup', 'bike')`);
        await queryRunner.query(`CREATE TABLE "drivers" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "city_id" uuid NOT NULL, "status" "public"."drivers_status_enum" NOT NULL DEFAULT 'pending_approval', "vehicleType" "public"."drivers_vehicletype_enum" NOT NULL, "vehicle_plate" character varying(50) NOT NULL, "vehicle_model" character varying(100), "last_lat" numeric(10,7), "last_lng" numeric(10,7), "last_seen_at" TIMESTAMP, "rating" numeric(3,2) NOT NULL DEFAULT '5', "total_trips" integer NOT NULL DEFAULT '0', "documents" jsonb, "documents_verified" boolean NOT NULL DEFAULT false, "accepts_cash" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_8e224f1b8f05ace7cfc7c76d03b" UNIQUE ("user_id"), CONSTRAINT "PK_92ab3fb69e566d3eb0cae896047" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_drivers_location" ON "drivers" ("last_lat", "last_lng") `);
        await queryRunner.query(`CREATE INDEX "idx_drivers_vehicle" ON "drivers" ("vehicleType", "status") `);
        await queryRunner.query(`CREATE INDEX "idx_drivers_city_status" ON "drivers" ("city_id", "status") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "idx_drivers_user" ON "drivers" ("user_id") `);
        await queryRunner.query(`CREATE TYPE "public"."deliveries_status_enum" AS ENUM('pending', 'searching', 'accepted', 'picked_up', 'in_transit', 'delivered', 'failed', 'cancelled')`);
        await queryRunner.query(`CREATE TYPE "public"."deliveries_package_size_enum" AS ENUM('small', 'medium', 'large')`);
        await queryRunner.query(`CREATE TABLE "deliveries" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "sender_id" uuid NOT NULL, "driver_id" uuid, "city_id" uuid NOT NULL, "status" "public"."deliveries_status_enum" NOT NULL DEFAULT 'pending', "package_size" "public"."deliveries_package_size_enum" NOT NULL, "package_description" character varying(500) NOT NULL, "pickup_address" character varying(500) NOT NULL, "pickup_lat" numeric(10,7) NOT NULL, "pickup_lng" numeric(10,7) NOT NULL, "dropoff_address" character varying(500) NOT NULL, "dropoff_lat" numeric(10,7) NOT NULL, "dropoff_lng" numeric(10,7) NOT NULL, "recipient_name" character varying(100) NOT NULL, "recipient_phone" character varying(20) NOT NULL, "estimated_price" numeric(12,2) NOT NULL, "final_price" numeric(12,2), "currency" character varying(3) NOT NULL DEFAULT 'XOF', "confirmation_code" character varying(6), "payment_id" uuid, "is_paid" boolean NOT NULL DEFAULT false, "picked_up_at" TIMESTAMP, "delivered_at" TIMESTAMP, "metadata" jsonb, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_a6ef225c5c5f0974e503bfb731f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_del_city" ON "deliveries" ("city_id", "status") `);
        await queryRunner.query(`CREATE INDEX "idx_del_driver" ON "deliveries" ("driver_id", "status") `);
        await queryRunner.query(`CREATE INDEX "idx_del_sender" ON "deliveries" ("sender_id", "status", "created_at") `);
        await queryRunner.query(`CREATE TYPE "public"."cities_status_enum" AS ENUM('active', 'inactive', 'coming_soon')`);
        await queryRunner.query(`CREATE TABLE "cities" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(100) NOT NULL, "slug" character varying(100) NOT NULL, "country_code" character varying(3) NOT NULL DEFAULT 'BF', "currency" character varying(3) NOT NULL DEFAULT 'XOF', "status" "public"."cities_status_enum" NOT NULL DEFAULT 'active', "center_lat" numeric(10,7) NOT NULL, "center_lng" numeric(10,7) NOT NULL, "radius_km" integer NOT NULL DEFAULT '30', "config" jsonb, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_8ef722e770798e37b3205370bfd" UNIQUE ("slug"), CONSTRAINT "PK_4762ffb6e5d198cfec5606bc11e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_cities_country" ON "cities" ("country_code", "status") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "idx_cities_slug" ON "cities" ("slug") `);
        await queryRunner.query(`CREATE TYPE "public"."system_announcements_type_enum" AS ENUM('info', 'maintenance', 'promotion', 'alert', 'update')`);
        await queryRunner.query(`CREATE TYPE "public"."system_announcements_status_enum" AS ENUM('draft', 'scheduled', 'published', 'archived')`);
        await queryRunner.query(`CREATE TYPE "public"."system_announcements_scope_enum" AS ENUM('global', 'city')`);
        await queryRunner.query(`CREATE TYPE "public"."system_announcements_media_type_enum" AS ENUM('image', 'video')`);
        await queryRunner.query(`CREATE TABLE "system_announcements" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_by" uuid NOT NULL, "title" character varying(250) NOT NULL, "content" text NOT NULL, "short_description" character varying(100), "type" "public"."system_announcements_type_enum" NOT NULL DEFAULT 'info', "status" "public"."system_announcements_status_enum" NOT NULL DEFAULT 'draft', "scope" "public"."system_announcements_scope_enum" NOT NULL DEFAULT 'global', "city_id" uuid, "channels" jsonb NOT NULL DEFAULT '["push","in_app","websocket"]', "pinned" boolean NOT NULL DEFAULT false, "action_url" text, "media_url" text, "media_type" "public"."system_announcements_media_type_enum", "media_thumbnail_url" text, "metadata" jsonb, "target_roles" jsonb, "published_at" TIMESTAMP WITH TIME ZONE, "expires_at" TIMESTAMP WITH TIME ZONE, "broadcast_id" uuid, "scheduled_at" TIMESTAMP WITH TIME ZONE, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, CONSTRAINT "PK_6cee838ddfb9eacd26af68db531" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_ann_scheduled_at" ON "system_announcements" ("scheduled_at") `);
        await queryRunner.query(`CREATE INDEX "idx_ann_expires_at" ON "system_announcements" ("expires_at") `);
        await queryRunner.query(`CREATE INDEX "idx_ann_published_at" ON "system_announcements" ("published_at") `);
        await queryRunner.query(`CREATE INDEX "idx_ann_city_status" ON "system_announcements" ("city_id", "status") `);
        await queryRunner.query(`CREATE INDEX "idx_ann_status_scope" ON "system_announcements" ("status", "scope") `);
        await queryRunner.query(`CREATE TABLE "announcement_reads" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "announcement_id" uuid NOT NULL, "read_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "uq_ann_read_user_ann" UNIQUE ("user_id", "announcement_id"), CONSTRAINT "PK_d82327e564612085a67f912bfae" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_ann_read_user" ON "announcement_reads" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "idx_ann_read_announcement" ON "announcement_reads" ("announcement_id") `);
        await queryRunner.query(`CREATE TYPE "public"."announcement_audit_logs_action_enum" AS ENUM('created', 'updated', 'scheduled', 'published', 'archived', 'deleted', 'duplicated', 'republished')`);
        await queryRunner.query(`CREATE TABLE "announcement_audit_logs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "announcement_id" uuid NOT NULL, "admin_id" uuid, "action" "public"."announcement_audit_logs_action_enum" NOT NULL, "meta" jsonb, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_d3e55c1a8d5afddd47eea8eaa46" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_ann_audit_created_at" ON "announcement_audit_logs" ("created_at") `);
        await queryRunner.query(`CREATE INDEX "idx_ann_audit_admin" ON "announcement_audit_logs" ("admin_id") `);
        await queryRunner.query(`CREATE INDEX "idx_ann_audit_announcement" ON "announcement_audit_logs" ("announcement_id") `);
        await queryRunner.query(`CREATE TABLE "permissions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "slug" character varying(100) NOT NULL, "resource" character varying(100) NOT NULL, "action" character varying(100) NOT NULL, "description" text, "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_d090ad82a0e97ce764c06c7b312" UNIQUE ("slug"), CONSTRAINT "PK_920331560282b8bd21bb02290df" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_perms_resource" ON "permissions" ("resource") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "idx_perms_slug" ON "permissions" ("slug") `);
        await queryRunner.query(`CREATE TABLE "role_permissions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "role_id" uuid NOT NULL, "permission_id" uuid NOT NULL, "granted_by" uuid, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_84059017c90bfcb701b8fa42297" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "idx_rp_unique" ON "role_permissions" ("role_id", "permission_id") `);
        await queryRunner.query(`CREATE INDEX "idx_rp_permission" ON "role_permissions" ("permission_id") `);
        await queryRunner.query(`CREATE INDEX "idx_rp_role" ON "role_permissions" ("role_id") `);
        await queryRunner.query(`CREATE TYPE "public"."roles_scope_enum" AS ENUM('global', 'city')`);
        await queryRunner.query(`CREATE TABLE "roles" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(100) NOT NULL, "slug" character varying(100) NOT NULL, "scope" "public"."roles_scope_enum" NOT NULL DEFAULT 'city', "description" text, "color" character varying(20), "is_system" boolean NOT NULL DEFAULT false, "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_881f72bac969d9a00a1a29e1079" UNIQUE ("slug"), CONSTRAINT "PK_c1433d71a4838793a49dcad46ab" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_roles_scope" ON "roles" ("scope") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "idx_roles_slug" ON "roles" ("slug") `);
        await queryRunner.query(`CREATE TABLE "user_roles" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "role_id" uuid NOT NULL, "city_id" uuid, "granted_by" uuid NOT NULL, "expires_at" TIMESTAMP, "is_active" boolean NOT NULL DEFAULT true, "reason" text, "granted_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_8acd5cf26ebd158416f477de799" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_ur_user_city" ON "user_roles" ("user_id", "city_id") `);
        await queryRunner.query(`CREATE INDEX "idx_ur_city" ON "user_roles" ("city_id") `);
        await queryRunner.query(`CREATE INDEX "idx_ur_role" ON "user_roles" ("role_id") `);
        await queryRunner.query(`CREATE INDEX "idx_ur_user" ON "user_roles" ("user_id", "is_active") `);
        await queryRunner.query(`CREATE TYPE "public"."audit_logs_outcome_enum" AS ENUM('allowed', 'denied', 'error')`);
        await queryRunner.query(`CREATE TABLE "audit_logs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid, "active_roles" character varying(200), "action" character varying(100) NOT NULL, "resource" character varying(100) NOT NULL, "resource_id" uuid, "city_id" uuid, "outcome" "public"."audit_logs_outcome_enum" NOT NULL, "denial_reason" text, "ip_address" character varying(45), "user_agent" text, "http_method" character varying(10), "request_path" text, "metadata" jsonb, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_1bb179d048bbc581caa3b013439" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_al_city" ON "audit_logs" ("city_id", "created_at") `);
        await queryRunner.query(`CREATE INDEX "idx_al_resource" ON "audit_logs" ("resource", "resource_id") `);
        await queryRunner.query(`CREATE INDEX "idx_al_outcome" ON "audit_logs" ("outcome", "created_at") `);
        await queryRunner.query(`CREATE INDEX "idx_al_user" ON "audit_logs" ("user_id", "created_at") `);
        await queryRunner.query(`ALTER TABLE "notification_delivery_logs" ADD CONSTRAINT "FK_222d7564d68c0c89c51d7ad4569" FOREIGN KEY ("notification_id") REFERENCES "notifications"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "role_permissions" ADD CONSTRAINT "FK_178199805b901ccd220ab7740ec" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "role_permissions" ADD CONSTRAINT "FK_17022daf3f885f7d35423e9971e" FOREIGN KEY ("permission_id") REFERENCES "permissions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_roles" ADD CONSTRAINT "FK_b23c65e50a758245a33ee35fda1" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "user_roles" DROP CONSTRAINT "FK_b23c65e50a758245a33ee35fda1"`);
        await queryRunner.query(`ALTER TABLE "role_permissions" DROP CONSTRAINT "FK_17022daf3f885f7d35423e9971e"`);
        await queryRunner.query(`ALTER TABLE "role_permissions" DROP CONSTRAINT "FK_178199805b901ccd220ab7740ec"`);
        await queryRunner.query(`ALTER TABLE "notification_delivery_logs" DROP CONSTRAINT "FK_222d7564d68c0c89c51d7ad4569"`);
        await queryRunner.query(`DROP INDEX "public"."idx_al_user"`);
        await queryRunner.query(`DROP INDEX "public"."idx_al_outcome"`);
        await queryRunner.query(`DROP INDEX "public"."idx_al_resource"`);
        await queryRunner.query(`DROP INDEX "public"."idx_al_city"`);
        await queryRunner.query(`DROP TABLE "audit_logs"`);
        await queryRunner.query(`DROP TYPE "public"."audit_logs_outcome_enum"`);
        await queryRunner.query(`DROP INDEX "public"."idx_ur_user"`);
        await queryRunner.query(`DROP INDEX "public"."idx_ur_role"`);
        await queryRunner.query(`DROP INDEX "public"."idx_ur_city"`);
        await queryRunner.query(`DROP INDEX "public"."idx_ur_user_city"`);
        await queryRunner.query(`DROP TABLE "user_roles"`);
        await queryRunner.query(`DROP INDEX "public"."idx_roles_slug"`);
        await queryRunner.query(`DROP INDEX "public"."idx_roles_scope"`);
        await queryRunner.query(`DROP TABLE "roles"`);
        await queryRunner.query(`DROP TYPE "public"."roles_scope_enum"`);
        await queryRunner.query(`DROP INDEX "public"."idx_rp_role"`);
        await queryRunner.query(`DROP INDEX "public"."idx_rp_permission"`);
        await queryRunner.query(`DROP INDEX "public"."idx_rp_unique"`);
        await queryRunner.query(`DROP TABLE "role_permissions"`);
        await queryRunner.query(`DROP INDEX "public"."idx_perms_slug"`);
        await queryRunner.query(`DROP INDEX "public"."idx_perms_resource"`);
        await queryRunner.query(`DROP TABLE "permissions"`);
        await queryRunner.query(`DROP INDEX "public"."idx_ann_audit_announcement"`);
        await queryRunner.query(`DROP INDEX "public"."idx_ann_audit_admin"`);
        await queryRunner.query(`DROP INDEX "public"."idx_ann_audit_created_at"`);
        await queryRunner.query(`DROP TABLE "announcement_audit_logs"`);
        await queryRunner.query(`DROP TYPE "public"."announcement_audit_logs_action_enum"`);
        await queryRunner.query(`DROP INDEX "public"."idx_ann_read_announcement"`);
        await queryRunner.query(`DROP INDEX "public"."idx_ann_read_user"`);
        await queryRunner.query(`DROP TABLE "announcement_reads"`);
        await queryRunner.query(`DROP INDEX "public"."idx_ann_status_scope"`);
        await queryRunner.query(`DROP INDEX "public"."idx_ann_city_status"`);
        await queryRunner.query(`DROP INDEX "public"."idx_ann_published_at"`);
        await queryRunner.query(`DROP INDEX "public"."idx_ann_expires_at"`);
        await queryRunner.query(`DROP INDEX "public"."idx_ann_scheduled_at"`);
        await queryRunner.query(`DROP TABLE "system_announcements"`);
        await queryRunner.query(`DROP TYPE "public"."system_announcements_media_type_enum"`);
        await queryRunner.query(`DROP TYPE "public"."system_announcements_scope_enum"`);
        await queryRunner.query(`DROP TYPE "public"."system_announcements_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."system_announcements_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."idx_cities_slug"`);
        await queryRunner.query(`DROP INDEX "public"."idx_cities_country"`);
        await queryRunner.query(`DROP TABLE "cities"`);
        await queryRunner.query(`DROP TYPE "public"."cities_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."idx_del_sender"`);
        await queryRunner.query(`DROP INDEX "public"."idx_del_driver"`);
        await queryRunner.query(`DROP INDEX "public"."idx_del_city"`);
        await queryRunner.query(`DROP TABLE "deliveries"`);
        await queryRunner.query(`DROP TYPE "public"."deliveries_package_size_enum"`);
        await queryRunner.query(`DROP TYPE "public"."deliveries_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."idx_drivers_user"`);
        await queryRunner.query(`DROP INDEX "public"."idx_drivers_city_status"`);
        await queryRunner.query(`DROP INDEX "public"."idx_drivers_vehicle"`);
        await queryRunner.query(`DROP INDEX "public"."idx_drivers_location"`);
        await queryRunner.query(`DROP TABLE "drivers"`);
        await queryRunner.query(`DROP TYPE "public"."drivers_vehicletype_enum"`);
        await queryRunner.query(`DROP TYPE "public"."drivers_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."idx_fo_user"`);
        await queryRunner.query(`DROP INDEX "public"."idx_fo_restaurant"`);
        await queryRunner.query(`DROP INDEX "public"."idx_fo_driver"`);
        await queryRunner.query(`DROP TABLE "food_orders"`);
        await queryRunner.query(`DROP TYPE "public"."food_orders_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."idx_rest_city"`);
        await queryRunner.query(`DROP INDEX "public"."idx_rest_slug"`);
        await queryRunner.query(`DROP TABLE "restaurants"`);
        await queryRunner.query(`DROP INDEX "public"."idx_broadcast_status"`);
        await queryRunner.query(`DROP INDEX "public"."idx_broadcast_city_role"`);
        await queryRunner.query(`DROP TABLE "broadcast_notifications"`);
        await queryRunner.query(`DROP TYPE "public"."broadcast_notifications_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."idx_ndl_notification"`);
        await queryRunner.query(`DROP INDEX "public"."idx_ndl_status"`);
        await queryRunner.query(`DROP TABLE "notification_delivery_logs"`);
        await queryRunner.query(`DROP TYPE "public"."notification_delivery_logs_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."notification_delivery_logs_channel_enum"`);
        await queryRunner.query(`DROP INDEX "public"."idx_notif_user"`);
        await queryRunner.query(`DROP INDEX "public"."idx_notif_unread"`);
        await queryRunner.query(`DROP INDEX "public"."idx_notif_category"`);
        await queryRunner.query(`DROP INDEX "public"."idx_notif_scheduled"`);
        await queryRunner.query(`DROP INDEX "public"."idx_notif_city"`);
        await queryRunner.query(`DROP TABLE "notifications"`);
        await queryRunner.query(`DROP TYPE "public"."notifications_priority_enum"`);
        await queryRunner.query(`DROP TYPE "public"."notifications_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."notifications_category_enum"`);
        await queryRunner.query(`DROP TYPE "public"."notifications_channel_enum"`);
        await queryRunner.query(`DROP INDEX "public"."idx_cpc_city_provider"`);
        await queryRunner.query(`DROP TABLE "city_payment_configs"`);
        await queryRunner.query(`DROP INDEX "public"."idx_payments_user"`);
        await queryRunner.query(`DROP INDEX "public"."idx_payments_reference"`);
        await queryRunner.query(`DROP INDEX "public"."idx_payments_provider_tx"`);
        await queryRunner.query(`DROP INDEX "public"."idx_payments_pending"`);
        await queryRunner.query(`DROP TABLE "payments"`);
        await queryRunner.query(`DROP TYPE "public"."payments_provider_enum"`);
        await queryRunner.query(`DROP TYPE "public"."payments_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."payments_service_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."idx_cpc_city_service_active"`);
        await queryRunner.query(`DROP INDEX "public"."idx_cpc_city_service_priority"`);
        await queryRunner.query(`DROP TABLE "city_pricing_configs"`);
        await queryRunner.query(`DROP TYPE "public"."city_pricing_configs_service_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."idx_pricing_city_service"`);
        await queryRunner.query(`DROP INDEX "public"."idx_pricing_priority"`);
        await queryRunner.query(`DROP TABLE "pricing_rules"`);
        await queryRunner.query(`DROP TYPE "public"."pricing_rules_service_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."idx_rp_city_active"`);
        await queryRunner.query(`DROP INDEX "public"."idx_rp_global_active"`);
        await queryRunner.query(`DROP TABLE "referral_programs"`);
        await queryRunner.query(`DROP TYPE "public"."referral_programs_referee_reward_type_enum"`);
        await queryRunner.query(`DROP TYPE "public"."referral_programs_referrer_reward_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."idx_rrl_usage"`);
        await queryRunner.query(`DROP INDEX "public"."idx_rrl_referrer"`);
        await queryRunner.query(`DROP INDEX "public"."idx_rrl_referee"`);
        await queryRunner.query(`DROP INDEX "public"."idx_rrl_city_service"`);
        await queryRunner.query(`DROP INDEX "public"."idx_rrl_program"`);
        await queryRunner.query(`DROP INDEX "public"."idx_rrl_idempotency"`);
        await queryRunner.query(`DROP TABLE "referral_reward_logs"`);
        await queryRunner.query(`DROP TYPE "public"."referral_reward_logs_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."referral_reward_logs_recipient_role_enum"`);
        await queryRunner.query(`DROP INDEX "public"."idx_ru_referrer"`);
        await queryRunner.query(`DROP INDEX "public"."idx_ru_referee"`);
        await queryRunner.query(`DROP INDEX "public"."idx_ru_program"`);
        await queryRunner.query(`DROP INDEX "public"."idx_ru_city_program"`);
        await queryRunner.query(`DROP TABLE "referral_usages"`);
        await queryRunner.query(`DROP TYPE "public"."referral_usages_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."idx_rml_ride"`);
        await queryRunner.query(`DROP INDEX "public"."idx_rml_user"`);
        await queryRunner.query(`DROP TABLE "ride_modification_logs"`);
        await queryRunner.query(`DROP TYPE "public"."ride_modification_logs_phase_enum"`);
        await queryRunner.query(`DROP TYPE "public"."ride_modification_logs_field_enum"`);
        await queryRunner.query(`DROP INDEX "public"."idx_rides_user_status"`);
        await queryRunner.query(`DROP INDEX "public"."idx_rides_driver_status"`);
        await queryRunner.query(`DROP INDEX "public"."idx_rides_city"`);
        await queryRunner.query(`DROP INDEX "public"."idx_rides_scheduled"`);
        await queryRunner.query(`DROP INDEX "public"."idx_rides_status"`);
        await queryRunner.query(`DROP TABLE "rides"`);
        await queryRunner.query(`DROP TYPE "public"."rides_cancelled_by_enum"`);
        await queryRunner.query(`DROP TYPE "public"."rides_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."rides_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."idx_user_kyc_user"`);
        await queryRunner.query(`DROP INDEX "public"."idx_user_kyc_status"`);
        await queryRunner.query(`DROP TABLE "user_kyc"`);
        await queryRunner.query(`DROP TYPE "public"."user_kyc_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."idx_users_phone"`);
        await queryRunner.query(`DROP INDEX "public"."idx_users_email"`);
        await queryRunner.query(`DROP INDEX "public"."idx_users_referral"`);
        await queryRunner.query(`DROP INDEX "public"."idx_users_city_status"`);
        await queryRunner.query(`DROP INDEX "public"."idx_users_created"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP TYPE "public"."users_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."idx_wtx_wallet"`);
        await queryRunner.query(`DROP INDEX "public"."idx_wtx_reference"`);
        await queryRunner.query(`DROP INDEX "public"."idx_wtx_wallet_type"`);
        await queryRunner.query(`DROP TABLE "wallet_transactions"`);
        await queryRunner.query(`DROP TYPE "public"."wallet_transactions_reason_enum"`);
        await queryRunner.query(`DROP TYPE "public"."wallet_transactions_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."idx_wallets_user"`);
        await queryRunner.query(`DROP TABLE "wallets"`);
        await queryRunner.query(`DROP TYPE "public"."wallets_status_enum"`);
    }

}
